### ISSUE TITLE
leetronics certificate expired

### ISSUE THREAD

**Issue by csylvain** [leetronics/infnoise#25]
ERROR: cannot verify 13-37.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.

**Comment by manuel-domke** [comment]
It would be helpful if you could include the service and port. For HTTPS of 13-37.org, it's already been fixed...

**Comment by csylvain** [comment]
then it is already fixed. for a while there, though, in `https://leetronics.de/en/blog/2017/07/24/packages-for-infinite-noise-trng/` at `To ensure authenticity of the packages, please add my PGP code signing key to your apt key-ring:` and trying to obtain the key would produce the notification. i tried to add a comment at the bottom of that page, but the recaptcha would always fail for me.
