### ISSUE TITLE
PGP-Key 0x4E730A3C expired 

### ISSUE THREAD

**Issue by mrplumber** [leetronics/infnoise#28]
Hello,
It seems that GPG key 71AE099B262DC0B493E6EE71975DC25C4E730A3C expired on 2022-07-23. I could not find renewed one.

The actual problem is with Debian repository:
```
Err:4 http://repo.13-37.org stable InRelease
  The following signatures were invalid: EXPKEYSIG 975DC25C4E730A3C Code Signing Key 13-37.org <pkg@13-37.org>
```

**Comment by bazfum** [comment]
I am experiencing this as well, just bought one from Crowd Supply and can't add the repo due to expired key.

**Comment by manuel-domke** [comment]
PGP key expiry has been extended/renewed. Repository should be back up & running again. 
Now working on a new release (0.3.3)!
